artifact_uri: file:///C:/Users/User/Desktop/mlops-project/app/mlflowruns/315903361643259112/f081d2ce09fc45cd98ea3d7f62bec2f7/artifacts
end_time: 1686476925063
entry_point_name: ''
experiment_id: '315903361643259112'
lifecycle_stage: active
run_id: f081d2ce09fc45cd98ea3d7f62bec2f7
run_name: Carrots
run_uuid: f081d2ce09fc45cd98ea3d7f62bec2f7
source_name: ''
source_type: 4
source_version: ''
start_time: 1686476862326
status: 3
tags: []
user_id: User
