artifact_uri: file:///C:/Users/User/Desktop/mlops-project/app/mlflowruns/315903361643259112/faf672c3fcec4ab69b2f1c5ee7a2790c/artifacts
end_time: 1686476968402
entry_point_name: ''
experiment_id: '315903361643259112'
lifecycle_stage: active
run_id: faf672c3fcec4ab69b2f1c5ee7a2790c
run_name: Boysenberries
run_uuid: faf672c3fcec4ab69b2f1c5ee7a2790c
source_name: ''
source_type: 4
source_version: ''
start_time: 1686476862129
status: 3
tags: []
user_id: User
